name: TheAudioDB Cover Art
description: Fetch track info using TheAudioDB

schema:
  - key: baseUrl
    label: Base URL
    type: text
    default: https://www.theaudiodb.com/api/v1/json
    readonly: true
  - key: apiKey
    label: API Key
    type: text
    default: 123
    required: true
  - key: headers
    label: Headers
    type: keyvalue

enabled: true
type: track