name: Build Linux arm64

on:
  workflow_dispatch:

jobs:
  build-linux-arm64:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci --cpu=arm64 --os=linux

      - name: Build Linux arm64
        run: npm run build:linux -- --arm64

      # - name: Normalize artifact names
      #   shell: bash
      #   run: |
      #     mv dist/pulse-player-*.AppImage \
      #       dist/pulse-player-linux-arm64.AppImage

      #     mv dist/pulse-player-*.deb \
      #       dist/pulse-player-linux-arm64.deb

      #     mv dist/pulse-player-*.tar.gz \
      #       dist/pulse-player-linux-arm64.tar.gz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: dist/
          if-no-files-found: error
      
